# This is a basic workflow to help you get started with Actions

on: [push]

name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true
      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          inlineScript: az account show
          azPSVersion: "latest"
